### ISSUE TITLE
Issue with pillow library compilation during install with PIP

### ISSUE THREAD

**Issue by anand7v** [AI4LIFE-GROUP/OpenXAI#11]
Hello Team,

I am Anand from University of Stuttgart, pursuing my doctoral research. While installing the open XAI using PIP command there is a compilation error reported with respect to pillow..

    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    _warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.clang-format'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'_
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
        
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.

Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8_fu5dva/pillow/setup.py", line 1037, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-8_fu5dva/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-p4qugs1n-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-8_fu5dva/pillow/

Am I missing some thing else in the setup (error message says some header files and other file extensions are missing)

Your feedback would be of great help!

Thanks in advance

Best regards,
Anand

**Comment by jiaqima** [comment]
Hi Anand,

Thanks for your question. Pillow is not a direct dependency of OpenXAI but a lower-level dependency. Unfortunately, this seems to be an environment-specific issue, which we could not help with much.

**Comment by anand7v** [comment]
Thanks for the response
