### ISSUE TITLE
[FEATURE REQUEST] Support for regression based problems

### ISSUE THREAD

**Issue by tabularaza27** [AI4LIFE-GROUP/OpenXAI#13]
Are you planning to add support for regression tasks ? 
If so, I'd suggest replacing the exact equality condition of the original and perturbed input predictions in the stability metrics (`ŷ_x == ŷ_x'`)  to something like `|ŷ_x- ŷ_x'|< eps`, where eps is a user-defined range.

**Comment by ehsankiakojouri** [comment]
For Ground_truth evaluations, one could use benchmark functions used in optimization like [Ackley](https://www.sfu.ca/~ssurjano/ackley.html) (or any other known mathematical functions) and fit several linear regression models for several particular ranges of inputs. Weights of linear regression models could be used as ground truth for faithfulness metrics.
