### ISSUE TITLE
How to split train and test datasets into different ratios using the OpenXAI Data loader

### ISSUE THREAD

**Issue by panigrahidileep** [AI4LIFE-GROUP/OpenXAI#19]
Dear Team,

I would like to split my train and test datasets into different ratios using the OpenXAI Data loader. I have reviewed the OpenXAI readme and it mentions the ability to customize the train-test split percentages. Can you confirm if this feature is available and provide guidance on how to perform the split.

Thankyou

**Comment by chirag126** [comment]
Hey panigrahidileep,

Thank you for your interest in our work. You would have to write a new function in [dataloader.py](https://github.com/AI4LIFE-GROUP/OpenXAI/blob/1fd06155ae8b64e969266c6ed2c4514c85f5615b/openxai/dataloader.py) for splitting the datasets into custom training and testing splits.
