### ISSUE TITLE
Not install using the pip command

### ISSUE THREAD

**Issue by ripankundu** [AI4LIFE-GROUP/OpenXAI#2]
Hi,

I am trying to use the OpenXAI tool in the google colab environment. But when I using the pip command the following error is show:

"ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /content"

Could you please provide any solution of this problem.

**Comment by y12uc231** [comment]
Do you mind sharing the exact pip command, and the complete stack trace for me to reproduce the error? Thanks!

**Comment by ripankundu** [comment]
Thank you for your quick response . The command is in the below:
pip install -e .

However, I tried with the command  "pip install -e ". Then the following problem is arise

**Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

-e option requires 1 argument**

**Comment by jiaqima** [comment]
> However, I tried with the command "pip install -e ". Then the following problem is arise

Did you miss the dot in your command?

It should be `pip install -e .` instead of `pip install -e`

**Comment by ripankundu** [comment]
@jiaqima  I also used pip install -e . for installing the openXAI in the google colab but the following error is raised:

ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /content

**Comment by jiaqima** [comment]
Hi @ripankundu, you have to be in the OpenXAI root folder to run `pip install -e .`. I'm not sure how to locate the folder in colab though.
