### ISSUE TITLE
question about German dataset

### ISSUE THREAD

**Issue by NKUShaw** [AI4LIFE-GROUP/OpenXAI#27]
Can you provide me the german-feature-metadata.p files? Thanks!

**Comment by adamdejl** [comment]
I have also been unsuccessfully trying to find the file, but it appears that it can be quite easily replaced by defining the feature metadata in the same way as in [faithfulness_demo.py](https://github.com/AI4LIFE-GROUP/OpenXAI/blob/2bae071737bddf0bfac2b2714964f08b996a8ab1/faithfulness_demo.py#L139). In particular, using the following code to initialise `input_dict['feature_metadata']` seems to be working for the German Credit dataset:
```
feature_metadata = dict()
feature_metadata['feature_n_cols'] = [1, 1, 1, 1, 1, 1, 1, 1, 4, 5, 10, 5, 5, 4, 3, 4, 3, 3, 4, 2]
feature_metadata['feature_types'] = ['c'] * 8 + ['d'] * 12
(...)
input_dict['feature_metadata'] = feature_metadata
```
