### ISSUE TITLE
Explicit versions of dependencies necessary?

### ISSUE THREAD

**Issue by fabiankueppers** [AI4LIFE-GROUP/OpenXAI#8]
Hi everyone,
after your fix in #7 for installation, explicit versions are assigned to each of the depent packages. Is this really necessary? At the moment, some dependent package versions conflict with my existing environments. Please ignore this issue if the explicit versions are really necessary, otherwise I would recommend to rather use "lower bounds" for the package versions.
Thank you!

**Comment by jiaqima** [comment]
Thank you for the suggestion. @eshika could you change it to the lower bound?

**Comment by eshika** [comment]
Thanks, will do!
